version: "3"

services:
  wireguard-helper:
    build: .
    container_name: wireguard-helper
    privileged: true # Required for WireGuard and iptables
    network_mode: host # Required for proper network access
    volumes:
      - /etc/wireguard:/etc/wireguard # Persist WireGuard configuration
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-your_secure_password_here} # Use environment variable with fallback
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 128M
